# Generated by Django 5.2b1 on 2026-04-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo of the field', null=True, upload_to='field_images/'),
        ),
    ]
